#NODE Container
FROM node:lts-alpine3.11 as node_stage

WORKDIR /app

#Install dependencies.
COPY ./frontend/package*.json ./
RUN npm install

#Copy source
# COPY ./ .
# COPY ./docker/nginx.conf /etc/nginx/nginx.conf
# COPY ./docker/htpasswd /etc/nginx/htpasswd

EXPOSE 5000

#Serve application in dev mode.
CMD npm i && npm run dev